### ISSUE TITLE
SoundCloud embeds don't scale

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/q-android#3] opened 2016-07-23 16:38 UTC
As they don't scale, the app allows you to scroll side to side in the post view. See https://play.google.com/store/apps/details?id=online.mindmusic for an example of this.

**Comment by blupu** [comment] 2016-07-23 21:56
Hi, you're right. Please check the feat-soundcloud branch's _functions.js_: https://github.com/uncatcrea/q-android/blob/feat-soundcloud/js/functions.js#L761

**I've added a quick and dirty patch to make SoundCloud embeds responsive. (Basically, I set their with to 100%.)**
- I assume that SoundCloud's embeds are integrated with the WordPress support
- It generates an iframe with a _data-src_ attribute
- I search for the value _soundcloud.com/player_ value in the _data-src_ value
- If I find it, I consider that this is a SoundCloud player and I set its width to 100%

I'll have to figure a better way to do that later, I think.

**Comment by blupu** [comment] 2016-08-25 20:07
Hi I believe the problem is solved so I close the issue.

**Closed as completed by blupu** 2016-08-25 20:07 UTC
Labels: enhancement, embeds
